autoInstallPeers: true

catalogMode: manual

cleanupUnusedCatalogs: true

dedupeDirectDeps: false

minimumReleaseAgeExclude:
  - '@effect/platform-node-shared@4.0.0-beta.90'
  - '@effect/platform-node@4.0.0-beta.90'
  - '@effect/vitest@4.0.0-beta.90'
  - effect@4.0.0-beta.90

optimisticRepeatInstall: true

enableGlobalVirtualStore: false

resolvePeersFromWorkspaceRoot: true

shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - '@effect/platform-node@4.0.0-beta.90'
  - '@effect/platform-node-shared@4.0.0-beta.90'
  - '@effect/vitest@4.0.0-beta.90'
  - effect@4.0.0-beta.90

packages:
  - apps/*
  - libs/*
  - packages/*

overrides:
  '@effect/platform-node-shared': 4.0.0-beta.90

catalog:
  '@antfu/eslint-config': ^9.0.0
  '@effect/language-service': 0.86.2
  '@effect/platform-node': 4.0.0-beta.90
  '@effect/tsgo': 0.14.6
  '@effect/vitest': 4.0.0-beta.90
  '@types/node': ^25.6.0
  '@typescript/native-preview': 7.0.0-dev.20260624.1
  effect: 4.0.0-beta.90
  eslint: ^10.3.0
  knip: ^6.12.0
  typescript: ^6.0.3
  vitest: ^4.1.8

updateConfig:
  ignoreDependencies:
    - typescript

verifyDepsBeforeRun: error

allowBuilds:
  msgpackr-extract: false
